<?php

echo "<h1>Bonjour pas d'inscription veuillez coder sa please </h1>";
/**** ENREGISTREMENT D'UN USER OU INSCRIPTION DE L'UTILISATEUR
 *
 *
 * CREER UN FORMULAIRE D'ENREGISTREMENT D'UN UTILISATEUR/USER QUI VA ENREGISTRER UN USER DANS LA BASE DE DONNEE
 * DANS LA TABLE USER
 *
 * POUR LE TYPE D'UTILISATEUR /typeUser SA DOIT ETRE UNE SELECT
 * <SELECT NAME="typeUser">
 *      <OPTION>etudiant</OPTION>
 *      <OPTION>enseignant</OPTION>
 *      <OPTION>admin</OPTION>
 * </SELECT>
 *
 * SVP RESPECTER LE NOM QUI SONT ECRIT DANS LES OPTION OU SINON ??????
 *
 * LES ATTRIBUT VOUS ALLER LES TROUVER DANS LA BASE DE DONNEE webisp
 *
 * */